spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iot_platform}
    username: ${SPRING_DATASOURCE_USERNAME:iot_user}
    password: ${SPRING_DATASOURCE_PASSWORD:iot_pass}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
